### PR TITLE
Add Strength Training activity type

### LINKED ISSUE #268: Weight / Strength Training
I'm trying to sync weight training activities between Strava, Runkeeper, and Garmin.

If I add a "Weight Training" activity to Strava:
- It doesn't seem to get picked up by tapiriik at all.

If I add a "Strength Training" activity to Garmin:
- It gets picked up by Tapiriik as a "Gym" activity.
- It appears in Strava as a "Workout". This has the correct title, start time, and duration. No calories, but I don't think Strava ever display calories for this type.
- It says "Runkeeper does not support this type of activity."

If I add a "Strength Training" activity to Runkeeper:
- It gets picked up by Tapiriik as an "Other" activity, with no name.
- It appears in Garmin as an "Other" type with the name "Other". The start time and calories are correct, but the duration is missing and the distance is 0 instead of blank.
- It says "Strava does not support this type of activity."

Ideally "Weight Training" in Strava, "Strength Training" in Runkeeper, and "Strength Training" in Garmin would all map to each other, and the title, start time, duration, and calories would be synced.

### PR DESCRIPTION
**Pull request by jamienicol**
Implemented for Garmin, Runkeeper, and Strava. Fixes #268 

I only did these three services as they are the only ones I use, and can therefore test.

### CODE REVIEW

**Comment by jamienicol** [comment]
I think the above test failure is unrelated to my change. I can reproduce locally on either master or my branch about 20% of the time I run the tests.

**Comment by jamienicol** [comment]
Been running this locally for a couple of weeks without any problems.

@cpfair, is there anything I can do to help move this along?

**Comment by cpfair** [comment]
Sorry for the delay!

**Comment by jamienicol** [comment]
Thanks!

**Pull request merged**
