### PR TITLE
Endomondo: Add power support and new sport mappings

### PR DESCRIPTION
**Pull request by clementsen**
- Add power_avg and power_max mappings
- Add new sport mappings
- Change some sport mappings
- Update some URLs

### CODE REVIEW

**Comment by clementsen** [comment]
@cpfair Are you able to look at this PR?

**Comment by Antash** [comment]
@clementsen I wonder how actually you develop this? Do you have access to endomondo api?

**Comment by clementsen** [comment]
@Antash Yes I work at Endomondo

**Comment by Antash** [comment]
@clementsen oh I see. May be you know is there a way to obtain api access for my application?

**Pull request merged**
