### PR TITLE
Replace garmin training list api

### LINKED ISSUE #416: 'Queuing' since about a week
I saw that since about a week my activities are not synchronized from Garmin to Strava.
I checked several times on the website, but Tapiriik is always 'Queuing'.
I've removed *all* connections and added them back, this didn't change anything.

(I've paid for automatic synchronization).

### PR DESCRIPTION
**Pull request by Antash**
Old api was not list activities starting from 21 March 2018.
resolve #416

### CODE REVIEW

**Comment by elskewe** [comment]
I can confirm that this fixes #416 locally with Vagrant.

**Comment by Antash** [comment]
Still need some work around garmin device. Need to discover api endpoint to obtain device information by its id coming with training summary. But this is not critical at all. I am even not sure someone use this stuff in tapiriik.

**Comment by cpfair** [comment]
Thanks a lot for submitting a PR for this! I just made a couple tweaks and merged it. You're right that the device ID wasn't really used - it does get baked into the TCX and FIT file exports so that the correct device can be displayed on other platforms, but that's hardly core functionality.

**Comment by habi** [comment]
Thanks for the fix!

**Pull request merged**
