### PR TITLE
Garmin/api fix

### PR DESCRIPTION
**Pull request by Antash**
Retired endpoint updated. Activities are able to be synced from CG

### CODE REVIEW

**Comment by cpfair** [comment]
Thanks for looking into this!

**Comment by stumurr** [comment]
Hi Antash, thanks for looking at this. I've tried to synch Garmin Connect and Dropbox but it won't synch any activities after the 14th Nov, even though Tapiriik shows successful synch after this time.

**Comment by rodneyha** [comment]
Samehere, since 6th of Nov, no more syncs even though Tapiriik shows successful sync.

**Comment by Antash** [comment]
Should work ok now.

**Comment by rodneyha** [comment]
Only thing what is happening:

afbeelding

**Comment by Antash** [comment]
I guess it can be 2 reasons:
1. (Most likely) You have no fresh activities since last sync error. Since Garmin supports triggered sync process manually pressing button will take no effect unless you get fresh activity or change settings to force next sync to be 'exaustive'
2. Fix is not deployed yet.

**Comment by Jancis** [comment]
I think @Antash is right, It's not deployed yet - master builds keep failing https://travis-ci.org/cpfair/tapiriik

**Comment by myke2241** [comment]
so what going on? i am loosing hope as nothing is syncing and tapiriik is always "queuing".

**Comment by cpfair** [comment]
This change was deployed shortly after it was merged.

**Comment by rodneyha** [comment]
Ok @cpfair thanks for the reply. Seems there is still an issue with Garmin Connect then. 
Since 6th of November no sync between GC and Dropbox (new activities are added on regular base in GC)

**Pull request merged**
