### PR TITLE
Update type hierarchy parsing in garminconnect.py

### PR DESCRIPTION
**Pull request by ppaavila**
Activity hierarchy format returned from Garmin Connect had been changed. Added two separate hash maps so parsing can be done on a single run.

### CODE REVIEW

**Comment by cpfair** [comment]
Thanks for improving this! Should speed up activity listings a bit...

**Comment by 850t5** [comment]
Could it be that this change crippled the sync capability with Garmin connect?
Since Jan 5th I'm getting error "Garmin Connect: There was a problem indexing your activities on Garmin Connect, so no activities will be uploaded to Garmin Connect."

**Comment by ppaavila** [comment]
> Could it be that this change crippled the sync capability with Garmin connect?
> Since Jan 5th I'm getting error "Garmin Connect: There was a problem indexing your activities on Garmin Connect, so no activities will be uploaded to Garmin Connect."

For me this fixed that issue, I got that very error before the change. The list of activity types is (and was) fetched from the url below:

https://connect.garmin.com/modern/proxy/activity-service/activity/activityTypes

With that format, mapping to parent must be done with ID. 

After this change Garmin sync has worked perfectly in my local instance and in tapiriik.com.

**Comment by 850t5** [comment]
Thanks, only use tapiriik.com and it worked flawless for the last time Jan 31st and failed for all subsequent activities (always just running) unfortunately. Don't think there is anything I can do to fix it on tapiriik.com myself?

**Comment by ppaavila** [comment]
> Thanks, only use tapiriik.com and it worked flawless for the last time Jan 31st and failed for all subsequent activities (always just running) unfortunately. Don't think there is anything I can do to fix it on tapiriik.com myself?

Send me mail (petri.paavilainen@iki.fi) with your contact info and we can try to sort this out in my instance.

**Comment by funwhilelost** [comment]
@ppaavila it looks like the master build is failing so your PR didn't make it out to the tapiriik public site.  @cpfair is there a chance you can get this out?  I'm seeing the same thing - Garmin Connect activities halt at the end of January.

**Comment by petpaa** [comment]
Must be something else, this was merged Jan 3rd, no changes after that. If your Garmin activities are not synced, change your Garmin password, unlink and link it agan to Tapiriik.com. If I understood right, this helped for @850t5.

**Pull request merged**
